name: Ruby Gem to PackageCloud

on:
  workflow_dispatch:
#  push:
#    branches: [ AO-18649_GH_build_actions ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    name: Build + Publish to PackageCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Publish to PackageCloud
        run: |
          echo 'gem: --no-document' >> ~/.gemrc
          rm -f Gemfile.lock
          bundle install --without development --without test
          bundle exec rake distclean
          bundle exec rake fetch_ext_deps
          echo `ls -l ext/oboe_metal/src`
          gem build appoptics_apm.gemspec
          gem install package_cloud
          # package_cloud push solarwinds/appoptics-apm-ruby *.gem
          # env:
          # PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
