name: !!! Ruby Gem to RubyGems !!!

on:
  workflow_dispatch:
    inputs:
      oboe_version:
        description: 'Oboe version to use with this gem version'
        required: true

jobs:
  build:
    name: Build + Release gem to RubyGems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6 and bundle
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install gems
        run: |
          echo 'gem: --no-document' >> ~/.gemrc
          bundle install --without development --without test

      - name: Install swig 4.0.2
        run: |
          curl -SL http://kent.dl.sourceforge.net/project/swig/swig/swig-4.0.2/swig-4.0.2.tar.gz | tar xzC /tmp
          cd /tmp/swig-4.0.2
          ./configure && make && make install
          cd -

      - name: Download oboe files from github, compile swig wrapper
        run: |
          bundle exec rake oboe_github_fetch ${{ github.event.inputs.oboe_version }} ${{ secrets.OBOE_TOKEN }}
          ls -l ext/oboe_metal/src

      - name: Verify downloaded files against production
        run: bundle exec rake verify_oboe_files

#      - name: Build Gem
#        run:  |
#          gem build appoptics_apm.gemspec
#          echo `shasum -a256 *.gem`

# - name: Add checksum to tag for gem release and publish tag

# - name: push to rubygems and check checksum


#      - name: Test install
#        TODO test if gem installs
