name: Ruby Gem to PackageCloud

on: [workflow_dispatch]

#  push:
#    branches: [ AO-18649_GH_build_actions ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    name: Build + Publish to PackageCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6 and bundle
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install gems
        run: |
          echo 'gem: --no-document' >> ~/.gemrc
          bundle install --without development --without test

      - name: Download oboe files from S3, compile swig wrapper
        run: |
          bundle exec rake fetch
          echo -e `ls -l ext/oboe_metal/src`

      - name: Build Gem
        run:  |
          gem build appoptics_apm.gemspec
          gem=`ls -dt1 builds/appoptics_apm-[^pre]*.gem | head -1`
          echo `shasum -a256 $gem`

      - name: Publish to PackageCloud
        run: |
          gem install package_cloud
          package_cloud yank solarwinds/appoptics-apm-ruby *.gem
          package_cloud push solarwinds/appoptics-apm-ruby *.gem
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

#      - name: Test install
#        TODO test if gem installs
