name: RELEASE Ruby Gem to RubyGems

on: [push]
#on:
#  workflow_dispatch:
#    inputs:
#      oboe_version:
#        description: 'Oboe version to use with this gem version'
#        required: true
#        default: 0.0.0

jobs:
  build:
    name: Build + Release Gem to RubyGems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6 and bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install gems
        run: |
          echo 'gem: --no-document' >> ~/.gemrc
          bundle install --without development --without test

      - name: Install swig 4.0.2
        run: |
          curl -SL http://kent.dl.sourceforge.net/project/swig/swig/swig-4.0.2/swig-4.0.2.tar.gz | tar xzC /tmp
          cd /tmp/swig-4.0.2
          ./configure && make && sudo make install
          cd -

      - name: Download oboe files from github, compile swig wrapper
        env:
          TRACE_BUILD_TOKEN: ${{ secrets.TRACE_BUILD_RUBY_ACTIONS_API_TOKEN }}
        run: |
          oboe_version=`cat ext/oboe_metal/src/VERSION`
          bundle exec rake oboe_github_fetch[$oboe_version]
          ls -l ext/oboe_metal/verify
          ls -l ext/oboe_metal/verify/bson

      - name: Download files from files.appoptics.com and github, and verify
        run: |
          oboe_version=`cat ext/oboe_metal/src/VERSION`
          bundle exec rake oboe_files_appoptics_fetch[$oboe_version]
          bundle exec rake oboe_verify

      - name: Build Gem and upload to Rubygems
        id: build
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_TOKEN }}
        run:  |
          bundle exec rake build_gem
          checksum=`shasum -a256 *.gem | awk '{print $1;}'`
          echo "checksum: $checksum"
          echo ::set-output name=checksum::$checksum
          echo ::set-output name=gem_version::`ruby -e 'require "./lib/appoptics_apm/version"; puts AppOpticsAPM::Version::STRING'`

      - name: get checksum from Rubygems
        id: checksum
        run: |
          gem_version=${{ steps.build.outputs.gem_version }}
          echo ::set-output name=geminfo::`curl https://rubygems.org/api/v2/rubygems/appoptics_apm/versions/$gem_version.json`

      - name: print checksums
        run: |
          echo "local checksum:    ${{ steps.build.outputs.checksum }}"
          echo "Rubygems checksum: ${{ fromJson(steps.checksum.outputs.geminfo).sha }}"

      - name: fail if local and rubygems checksum not matching
        if: fromJson(steps.checksum.outputs.geminfo).sha != steps.build.outputs.checksum
        run: |
          echo "local and rubygems checksum not matching"
          exit 1

      - name: Create release
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createRelease({
              owner: "appoptics",
              repo: "appoptics-apm-ruby",
              body: "SHA256 checksum: ${{ steps.build.outputs.checksum }}",
              tag_name: "${{ steps.build.outputs.gem_version }}",
              name: "${{ steps.build.outputs.gem_version }}",
              draft: true
            })

      # may need a bit of time for the gem to become available (sleep 1)
      - name: Test new Rubygem downloaded from Rubygems
        working-directory: .github/workflows/
        env:
          APPOPTICS_SERVICE_KEY: ${{ secrets.APPOPTICS_SERVICE_KEY }}
          APPOPTICS_COLLECTOR: ${{ secrets.APPOPTICS_COLLECTOR}}
        run: |
          sleep 1
          gem install appoptics_apm --version ${{ steps.build.outputs.gem_version }}
          ruby ./scripts/test_install.rb


