name: Build docker images

on:
  push:
    paths:
    - 'test/run_tests/Dockerfile_*'

jobs:

  build:
    name: Build docker images

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file test/run_tests/Dockerfile_ubuntu --tag ao_ubuntu
