name: Docker Image CI

on:
  push:
    paths:
    - 'test/run_tests/Docker_*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file test/run_tests/Dockerfile_ubuntu --tag ao_ubuntu
