name: Build docker images

on:
  push:
    paths:
    - 'test/run_tests/Dockerfile_*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  image: ghcr.io/appoptics/appoptics-apm-ruby/ao_ubuntu:latest
  dockerfile: test/run_tests/Dockerfile_ubuntu

jobs:

  build_push:
    name: Build docker images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: ghcr.io login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

#    - name: Build and push V2
#      uses: docker/build-push-action@v2
#      with:
#        file: test/run_tests/Dockerfile_ubuntu
#        tags: ghcr.io/appoptics/appoptics-apm-ruby/ao_ubuntu:latest
#        push: true

    - name: Build new Docker image
      run: docker build -f ${{ env.dockerfile }} -t ${{ env.image }} .

    - name: Publish updated Docker image
      run: docker push ${{ env.image }}
