name: Run all Tests

#on: [push, pull_request]
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
#        ruby: [3.0, 2.7, 2.6, 2.5, 2.4]
        ruby: [2.6]
        gemfile:
          - libraries
#          - unit
#          - instrumentation_mocked
#          - instrumentation_mocked_oldgems
#          - frameworks
#          - rails61
#          - rails60
#          - rails52
#          - rails42
#          - delayed_job
#          - noop
        dbtype: [postgresql, mysql2]
        exclude:
          - ruby: 3.0
            gemfile: rails42
          - ruby: 2.7sequel_mysql2_test.rb:10
            gemfile: rails42
          - ruby: 2.6
            gemfile: rails42
          - ruby: 2.4
            gemfile: rails61
          - ruby: 2.4
            gemfile: rails60
          - ruby: 2.4  # excluding because of new sprockets version (4.0.0)
            gemfile: rails52

          - gemfile: unit
            dbtype: mysql2
          - gemfile: noop
            dbtype: mysql2
          - gemfile: libraries
            dbtype: mysql2
          - gemfile: instrumentation_mocked
            dbtype: mysql2
          - gemfile: instrumentation_mocked_oldgems
            dbtype: mysql2
          - gemfile: frameworks
            dbtype: mysql2
          - gemfile: delayed_job
            dbtype: mysql2

    name: ${{ matrix.ruby }} - ${{ matrix.gemfile }}
#    name: Test Service Setup
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      APPOPTICS_GEM_TEST: true
      APPOPTICS_REPORTER: file
      APPOPTICS_COLLECTOR: /tmp/appoptics_traces.bson
      APPOPTICS_MONGO_SERVER: "ao-ruby-mongo"
      APPOPTICS_RABBITMQ_SERVER: "ao-ruby-rabbitmq"
      APPOPTICS_REPORTER_FILE_SINGLE: false
      APPOPTICS_FROM_S3: true
#      DBTYPE: mysql2
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_DATABASE: "travis_ci_test"
      POSTGRES_DB: "travis_ci_test"
      DOCKER_MYSQL_PASS: "admin"
      DOCKER_PSQL_PASS: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PSQL_HOST: "localhost"
    services:
#      ao-ruby-rabbitmq:
#        image: rabbitmq:3-management
#      ao-ruby-mongo:
#        image: mongo:3.4
      postgres:
        image: postgres:10.8
        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mariadb:latest
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: travis_ci_test
          MYSQL_ROOT_PASSWORD: admin
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y --no-install-recommends libcurl4-gnutls-dev libsasl2-dev

      - name: Set up ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Set database type env var
        run: export DBTYPE=${{ matrix.dbtype }}

      - name: Bundle with 1.17.3
        if: matrix.gemfile == 'rails42' || matrix.gemfile == 'frameworks'
        run: |
          gem install bundler:1.17.3
          export BUNDLE_GEMFILE=gemfiles/${{ matrix.gemfile }}.gemfile
          bundle _1.17.3_ install --jobs 4 --retry 3
      - name: Bundle
        if: matrix.gemfile != 'rails42' && matrix.gemfile != 'frameworks'
        run: |
          gem install bundler
          export BUNDLE_GEMFILE=gemfiles/${{ matrix.gemfile }}.gemfile
          bundle install --jobs 4 --retry 3

      - name: Install swig 4.0.2
        run: |
          curl -SL http://kent.dl.sourceforge.net/project/swig/swig/swig-4.0.2/swig-4.0.2.tar.gz | tar xzC /tmp
          cd /tmp/swig-4.0.2
          ./configure && make && sudo make install
          cd -
          rm -rf /tmp/swig-4.0.2

      - name: Compile c-extension
        run: |
          bundle exec rake fetch compile

      - name: Initialize services
        env:
          # use localhost for the host here because we are running the job on the VM.
          # If we were running the job on in a container this would be postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        run: |
          export PGPASSWORD=$POSTGRES_PASSWORD; psql -c 'create database travis_ci_test;' -U postgres -h localhost -p $POSTGRES_PORT
#          mysql -e 'create database travis_ci_test;'
#          redis-server --requirepass secret_pass

      - name: Run tests
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: bundle exec rake test
