name: Run all Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0.x, 2.7.x, 2.6.x, 2.5.x, 2.4.x]
        gemfile:
          - libraries.gemfile
          - unit.gemfile
          - instrumentation_mocked.gemfile
          - instrumentation_mocked_oldgems.gemfile
          - frameworks.gemfile
          - rails60.gemfile
          - rails52.gemfile
          - rails42.gemfile
          - delayed_job.gemfile
          - noop.gemfile
        exclude:
          - ruby: 3.0.x
            gemfile: rails42.gemfile
          - ruby: 2.7.x
            gemfile: rails42.gemfile
          - ruby: 2.6.x
            gemfile: rails42.gemfile
          - ruby: 2.4.x
            gemfile: rails60.gemfile
          - ruby: 2.4.x  # excluding because of new sprockets version (4.0.0)
            gemfile: rails52.gemfile

#          - gemfile: unit.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: noop.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: libraries.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: instrumentation_mocked.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: instrumentation_mocked_oldgems.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: frameworks.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: delayed_job.gemfile
#            env: DBTYPE=mysql2

    name: ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle ${{ matrix.gemfile }} with 1.17.3
        if: ${{ matrix.ruby  == "2.4.x" }}
        run: |
          gem install bundler:1.17.3
          export BUNDLE_GEMFILE=gemfiles/${{ matrix.gemfile }}
          bundle _1.17.3_ install --jobs 4 --retry 3
      - name: Bundle
        if: ${{ matrix.ruby != "2.4.x" }}
        run: |
          gem install bundler
          export BUNDLE_GEMFILE=gemfiles/${{ matrix.gemfile }}
          bundle install --jobs 4 --retry 3
