name: Run all Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0.x, 2.7.x, 2.6.x, 2.5.x, 2.4.x]
        gemfile:
          - libraries
          - unit
          - instrumentation_mocked
          - instrumentation_mocked_oldgems
          - frameworks
          - rails61
          - rails60
          - rails52
          - rails42
          - delayed_job
          - noop
        exclude:
          - ruby: 3.0.x
            gemfile: rails42
          - ruby: 2.7.x
            gemfile: rails42
          - ruby: 2.6.x
            gemfile: rails42
          - ruby: 2.4.x
            gemfile: rails61
          - ruby: 2.4.x
            gemfile: rails60
          - ruby: 2.4.x  # excluding because of new sprockets version (4.0.0)
            gemfile: rails52

#          - gemfile: unit
#            env: DBTYPE=mysql2
#          - gemfile: noop
#            env: DBTYPE=mysql2
#          - gemfile: libraries
#            env: DBTYPE=mysql2
#          - gemfile: instrumentation_mocked
#            env: DBTYPE=mysql2
#          - gemfile: instrumentation_mocked_oldgems
#            env: DBTYPE=mysql2
#          - gemfile: frameworks
#            env: DBTYPE=mysql2
#          - gemfile: delayed_job
#            env: DBTYPE=mysql2

    name: ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      APPOPTICS_GEM_TEST: true
      APPOPTICS_REPORTER: file
      APPOPTICS_COLLECTOR: /tmp/appoptics_traces.bson
      APPOPTICS_REPORTER_FILE_SINGLE: false
      APPOPTICS_FROM_S3: true
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y --no-install-recommends libcurl4-gnutls-dev libsasl2-dev

      - name: Set up ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Bundle with 1.17.3
        if: matrix.gemfile == 'rails42' || matrix.gemfile == 'frameworks'
        run: |
          gem install bundler:1.17.3
          export BUNDLE_GEMFILE=gemfiles/${{ matrix.gemfile }}.gemfile
          bundle _1.17.3_ install --jobs 4 --retry 3
      - name: Bundle
        if: matrix.gemfile != 'rails42' && matrix.gemfile != 'frameworks'
        run: |
          gem install bundler
          export BUNDLE_GEMFILE=gemfiles/${{ matrix.gemfile }}.gemfile
          bundle install --jobs 4 --retry 3

      - name: Install swig 4.0.2
        run: |
          curl -SL http://kent.dl.sourceforge.net/project/swig/swig/swig-4.0.2/swig-4.0.2.tar.gz | tar xzC /tmp
          cd /tmp/swig-4.0.2
          ./configure && make && sudo make install
          cd -
          rm -rf /tmp/swig-4.0.2

      - name: Compile c-extension
        run: |
          bundle exec rake fetch compile
#      - name: Set up services
      - name: Run tests
        run: bundle exec rake test
