name: Run all Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0.x, 2.7.x, 2.6.x, 2.5.x, 2.4.x]
        gemfile:
          - gemfiles/libraries.gemfile
          - gemfiles/unit.gemfile
          - gemfiles/instrumentation_mocked.gemfile
          - gemfiles/instrumentation_mocked_oldgems.gemfile
          - gemfiles/frameworks.gemfile
          - gemfiles/rails60.gemfile
          - gemfiles/rails52.gemfile
          - gemfiles/rails42.gemfile
          - gemfiles/delayed_job.gemfile
          - gemfiles/noop.gemfile
        exclude:
          - ruby: ruby-head
            gemfile: gemfiles/rails42.gemfile
          - ruby: 2.7.0
            gemfile: gemfiles/rails42.gemfile
          - ruby: 2.6.5
            gemfile: gemfiles/rails42.gemfile
          - ruby: 2.4.5
            gemfile: gemfiles/rails60.gemfile
          - ruby: 2.4.5  # excluding because of new sprockets version (4.0.0)
            gemfile: gemfiles/rails52.gemfile

#          - gemfile: gemfiles/unit.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: gemfiles/noop.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: gemfiles/libraries.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: gemfiles/instrumentation_mocked.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: gemfiles/instrumentation_mocked_oldgems.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: gemfiles/frameworks.gemfile
#            env: DBTYPE=mysql2
#          - gemfile: gemfiles/delayed_job.gemfile
#            env: DBTYPE=mysql2

    name: Ruby ${{ matrix.ruby }} - Gemfile ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up  ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby }}
      - name: Bundle ${{ matrix.gemfile }}
        run: |
          gem install bundler
          export BUNDLE_GEMFILE=${{ matrix.gemfile }}
          bundle install --jobs 4 --retry 3
