# Copyright (c) 2021 SolarWinds, LLC.
# All rights reserved.

name: C++ Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
#        ruby: [3.0, 2.7, 2.6, 2.5, 2.4]

    container:
      image: ruby:${{ matrix.ruby }}

    name: ${{ matrix.ruby }} - c++

    env:
      APPOPTICS_REPORTER: file
      APPOPTICS_COLLECTOR: /tmp/appoptics_traces.bson
      APPOPTICS_REPORTER_FILE_SINGLE: false
      APPOPTICS_FROM_S3: true

    steps:
      - uses: actions/checkout@v2

      - name: Install cmake and gtests
        run: |
          ls -lrt /usr/src
          apt update && apt install  -y --no-install-recommends build-essential libgtest-dev google-mock cmake ruby
          echo "list googletest:"
          ls -lrt /usr/src/googletest/googletest
          ls -lrt /usr/src/googletest/googlemock
          cd /usr/src/googletest/googletest && cmake CMakeLists.txt && make && cp *.a /usr/lib
          cd /usr/src/googletest/googlemock && cmake CMakeLists.txt && make && cp *.a /usr/lib

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install swig 4.0.2
        working-directory: .github/workflows/swig
        run: |
          apt update && apt install -y --no-install-recommends bison
          tar -xf swig-v4.0.2.tar.gz -C /tmp
          cd /tmp/swig-4.0.2
          ./autogen.sh && ./configure && make && make install
          cd -

      - name: Bundle & download c-files
        run: |
          gem install bundler
          bundle install
          bundle exec rake clean fetch compile

      - name: Compile and run tests
        working-directory: ext/oboe_metal/test
        run: |
          export RUBY_INC_DIR=$(ruby ruby_inc_dir.rb)
          export RUBY_PREFIX=$(ruby ruby_prefix.rb)
          cmake CMakeLists.txt
          make
          ./runTests
