# Copyright (c) 2021 SolarWinds, LLC.
# All rights reserved.

name: C++ Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0, 2.7, 2.6, 2.5, 2.4]

    container:
      image: ruby:${{ matrix.ruby }}

    name: ${{ matrix.ruby }} - c++

    env:
      APPOPTICS_REPORTER: file
      APPOPTICS_COLLECTOR: /tmp/appoptics_traces.bson
      APPOPTICS_REPORTER_FILE_SINGLE: false

    steps:
      - uses: actions/checkout@v2

      - name: Bundle & download c-files
        run: |
          gem install bundler
          bundle install
          bundle exec rake clean fetch compile

      - name: install gtests
        run: |
          apt update && apt install libgtest-dev google-mock cmake`
          cd /usr/src/gtest`
          cmake .
          make
          mv libg* /usr/lib/

      - name: compile and run tests
        run: |
          cd ext/oboe_metal/test
          cmake CMakeLists.txt
          make
          ./runTests
